### ISSUE TITLE
not opening files on linux or at all

### ISSUE THREAD

**Issue by vmishev** [e8johan/stl-viewer#1]

**Comment by vmishev** [comment]
not loading the .stl file at all

**Comment by e8johan** [comment]
Do you have a sample STL that fails?

**Comment by aytekno** [comment]
Not loading stl file. Program does not give error. I have changed the owl.stl file with a new file in my own directory.

**Comment by e8johan** [comment]
I downloaded this STL, renamed it and put it in the correct place, it works for me.

https://www.thingiverse.com/thing:18271

**Comment by aytekno** [comment]
Thank you Johan. I have a 3d scanner and I used your code to view my stl
file. After changing binary stl file to ascii stl file your code works very
well.

25 Ağu 2017 15:12 tarihinde "Johan Thelin" <notifications@github.com> yazdı:
