### ISSUE TITLE
How did you changed the stlviewer object class? 

### ISSUE THREAD

**Issue by aytekno** [e8johan/stl-viewer#3]
Hello,
Thank you for your code. I have tried and worked properly. I have a question. Inside mainwindow there is an stlviewer part. Is this a qwidget or qframe and also how did you changed the class of the object like stlviewer? 
Thank you.

**Comment by e8johan** [comment]
In the Designer view, you right click the widget and select to promote it. There you can provide a class name, what header to include and such.
